<?php
/**
 * @access protected
 * @author Judzhin Miles <info[woof-woof]msbios.com>
 */
namespace MSBios\CPanel;

// Add jses
$this->headScript()
    ->prependFile($this->basePath('limitless/assets/js/plugins/forms/inputs/formatter.min.js'))
    ->prependFile($this->basePath('limitless/ckeditor/ckeditor.js'))
;

/** @var \Zend\Form\Form $form */
$form = $this->form;
$form->prepare();
?>

<div class="panel panel-flat">

    <div class="panel-body">

        <?= $this->form()->openTag($form->setAttributes([
            'class' => 'form-horizontal',
            'role' => 'form'
        ])); ?>

        <?= $this->partial('partial/element.phtml', [
            'element' => $form->get('name')
                ->setAttributes([
                    'required' => 'required',
                    'placeholder' => $this->translate('Enter text page name')
                ]),
            'label' => $this->translate('Name'),
        ]); ?>

        <?= $this->partial('partial/element.phtml', [
            'element' => $form->get('slug')
                ->setAttributes([
                    'required' => 'required',
                    'placeholder' => $this->translate('Enter text page name')
                ]),
            'label' => $this->translate('Slug'),
        ]); ?>

        <?= $this->partial('partial/element.phtml', [
            'element' => $form->get('metaTitle')
                ->setAttributes([
                    'required' => 'required',
                    'placeholder' => $this->translate('Enter text page meta title')
                ]),
            'label' => $this->translate('Meta Title'),
        ]); ?>

        <?= $this->partial('partial/element.phtml', [
            'element' => $form->get('metaKeywords')
                ->setAttributes([
                    'required' => 'required',
                    'placeholder' => $this->translate('Enter text page meta keywords')
                ]),
            'label' => $this->translate('Meta Keywords'),
        ]); ?>

        <?= $this->partial('partial/element.phtml', [
            'element' => $form->get('metaDescription')
                ->setAttributes([
                    'required' => 'required',
                    'placeholder' => $this->translate('Enter text page meta description')
                ]),
            'label' => $this->translate('Meta Description'),
        ]); ?>

        <?= $this->partial('partial/element.phtml', [
            'element' => $form->get('content')
                ->setAttribute('id', 'content')
                ->setAttributes([
                    'required' => 'required',
                    'placeholder' => $this->translate('Enter text page content')
                ]),
            'label' => $this->translate('Content'),
        ]); ?>

        <?= $this->partial('partial/element.phtml', [
            'element' => $form->get('state')
                ->setAttributes([
                    'required' => 'required',
                    'placeholder' => $this->translate('Select state')
                ]),
            'label' => $this->translate('State'),
        ]); ?>

        <div class="text-right">
            <button type="reset" class="btn btn-default"><?= $this->translate('Reset'); ?></button>
            <button type="submit" class="btn btn-primary">
                <?= $this->translate('Submit'); ?>
                <i class="icon-arrow-right14 position-right"></i>
            </button>
        </div>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>

<?php $this->inlineScript()->captureStart(); ?>
    CKEDITOR.replace('content', {
        height: '250px'
    });
<?php $this->inlineScript()->captureEnd(); ?>