<?php
/**
 * @access protected
 * @author Judzhin Miles <info[woof-woof]msbios.com>
 */

namespace MSBios\Content\CPanel\Doctrine;

use MSBios\Content\Resource\Doctrine\Entity\TextPage;

$this->headScript()
    ->appendFile($this->basePath('limitless/assets/js/plugins/forms/styling/switch.min.js'))
    ->appendFile($this->basePath('limitless/assets/js/plugins/forms/styling/switchery.min.js'))
    ->appendFile($this->basePath('limitless/assets/js/plugins/forms/styling/uniform.min.js'));
?>

<div class="row">
    <div class="col-md-12">

        <?php if (!$this->paginator->count()) : ?>

            <div class="alert alert-info no-border" role="alert">
                <h4><?= $this->translate('Information message'); ?></h4>
                <p><?= $this->translate('The database is not created at the moment no text page, click "Create new text page" to start working with the text page.'); ?></p>
                <p>
                    <?php if ($this->isAllowed($this->resourceId, 'add')): ?>
                        <a href="<?= $this->url($this->matchedRouteName, ['action' => 'add']); ?>"
                           class="btn btn-info"><?= $this->translate('Create new text page'); ?></a>
                    <?php endif; ?>
                </p>
            </div>

        <?php else: ?>
            <div class="panel panel-flat">

                <div class="panel-heading">
                    <h6 class="panel-title">
                        &nbsp<a class="heading-elements-toggle"><i class="icon-more"></i></a>
                    </h6>
                    <div class="heading-elements">
                        <div class="heading-btn">
                            <?= $this->form()->openTag((new \Zend\Form\Form)->prepare()->setAttributes([
                                'class' => 'heading-form',
                                'method' => 'GET'
                            ]));
                            ?>
                            <div class="form-group has-feedback">
                                <?= $this->formSearch(
                                    (new \Zend\Form\Element\Search('q'))->setAttributes([
                                        'class' => 'form-control',
                                        'placeholder' => 'Search...'
                                    ])
                                ); ?>

                                <div class="form-control-feedback">
                                    <i class="icon-search4 text-size-base text-muted"></i>
                                </div>
                            </div>
                            <?= $this->form()->closeTag(); ?>

                            &nbsp;

                            <?php if ($this->isAllowed($this->resourceId, 'add')): ?>
                                <a href="<?= $this->url($this->matchedRouteName, ['action' => 'add']); ?>"
                                   class="btn btn-success"><?= $this->translate('Create new text page'); ?></a>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>

                <div class="panel-body">

                    <table class="table table-striped table-hover mails m-0 table table-actions-bar">
                        <thead>
                        <tr>
                            <th width="1px"></th>
                            <th><?= $this->translate('Name'); ?></th>
                            <th class="text-center"><?= $this->translate('State'); ?></th>
                            <th><?= $this->translate('Slug'); ?></th>
                            <th><?= $this->translate('Created At'); ?></th>
                            <th width="100px" class="text-center">
                                <?= $this->translate('Actions'); ?>
                            </th>
                        </tr>
                        </thead>

                        <tbody>
                        <?php /** @var TextPage $item */ ?>
                        <?php foreach ($this->paginator as $item): ?>
                            <tr>
                                <td>
                                    <a target="_blank" href="<?= $this->url('home/static', [
                                        'permalink' => $item->getSlug(),
                                        'format' => '.html'
                                    ]); ?>">
                                        <i class="icon-eye4"></i>
                                    </a>
                                </td>
                                <td><?= $this->escapeHtml($item->getName()); ?></td>
                                <td class="text-center">
                                    <span class="label border-info text-info-600">
                                        <?= $this->escapeHtml($item->getState()); ?>
                                    </span>
                                </td>
                                <td><?= $this->escapeHtml($item->getSlug()); ?></td>
                                <td>
                                    <?= $this->dateFormat(
                                        $item->getCreatedAt(),
                                        \IntlDateFormatter::MEDIUM,
                                        \IntlDateFormatter::SHORT);
                                    ?>
                                </td>
                                <td class="text-center">
                                    <?= $this->partial('partial/actions.phtml', [
                                        'matchedRouteName' => $this->matchedRouteName,
                                        'identifier' => $item->getId()
                                    ]); ?>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>

                    <?= $this->paginationControl($this->paginator, 'sliding', 'partial/pagination.phtml', [
                        'route' => $this->matchedRouteName
                    ]); ?>

                </div>

            </div>
        <?php endif; ?>

    </div> <!-- end col -->
</div>